# Generated by Django 4.1 on 2024-06-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(upload_to="profile_pictures/"),
        ),
    ]
